# -*- python -*-
Import("env")

# includedProducts lists packages with included .i files
env.CheckSwig("python", ilang="c++", includedProducts="utils afw detection")

env.LoadableModuleIncomplete("_kaiserLib", Split("kaiserLib.i"), LIBS=env.getlibs("coadd_kaiser"))
