# -*- python -*-
Import("env")
import sys

env.Program(["median.cc"], LIBS=env.getlibs("coadd_kaiser"))

import lsst.tests

dataDir = env.ProductDir("afwdata")
args = {
}
#
# Tests
#
ignoreList = [
]

if not dataDir:
    sys.stderr.write("afwdata is not set up; skipping tests requiring data\n")
    ignoreList += args.keys()

tests = lsst.tests.Control(env, args=args, ignoreList=ignoreList, verbose=True)
tests.run("*.cc")
#for target in tests.run("*.py"):
#    env.Depends(target, "../python/lsst/coadd/kaiser/_kaiserLib%s" % (env["LDMODULESUFFIX"]))
